name: Fast Forward After Merge

on:
  pull_request:
    types: [closed]  # Trigger when a PR targeting 'gitbook-publish' is merged

jobs:
  fast-forward-dev:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Fast-Forward gitbook-dev to gitbook-publish
        run: |
          git checkout gitbook-dev
          git merge --ff-only origin/gitbook-publish  # Fast-forward gitbook-dev

      - name: Push changes to gitbook-dev
        run: |
          git push origin gitbook-dev

